accum-grad: 2
adim: 256
aheads: 4
backend: pytorch
batch-size: 24
dlayers: 6
dropout-rate: 0.1
dunits: 2048
elayers: 6
epochs: 45
eunits: 2048
grad-clip: 5
join-train: st
lsm-weight: 0.1
maxlen-in: 512
maxlen-out: 150
model-module: espnet.nets.pytorch_backend.e2e_asr_st_transformer:E2E
mtlalpha: 0.3
opt: noam
patience: 0
report-bleu: true
report-cer: true
report-wer: true
sortagrad: 0
transformer-attn-dropout-rate: 0.0
transformer-init: pytorch
transformer-input-layer: conv2d
transformer-length-normalized-loss: false
transformer-lr: 5.0
transformer-warmup-steps: 25000
